"""initial migrate111

Revision ID: bf10d1b053eb
Revises: 
Create Date: 2025-03-26 01:14:04.824797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf10d1b053eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('service_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_review', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('professional_review', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
